name: Veracode Static Scan
on: workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      PUBLISH: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
        version: latest
    - uses: docker/login-action@v2
      if: ${{ env.PUBLISH }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=sha
          type=edge
          type=raw,value=latest,enable={{is_default_branch}}
    - uses: docker/build-push-action@v3
      id: build
      with:
        file: Dockerfile
        context: .
        push: ${{ env.PUBLISH }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  static_analysis:
    name: Static Analysis
    needs: build
    runs-on: ubuntu-latest
    env:
        VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2

      - name: Download CLI
        uses: wei/curl@master
        with:
          args: -fsS https://tools.veracode.com/veracode-cli/install | sh
          
      - name: Package Application
        run: ./veracode package -s . -o veracode-artifact -a trust
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'Go-Demo'
          createprofile: false
          filepath: 'veracode-artifact'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          createsandbox: 'false'

      - name: Veracode CLI Static Scan
        run: ./veracode static scan veracode-artifact/*


        
  
